RC-84
Aaron-G-9/reactjs-calendar pull request #87
Opened 2018-04-20 13:41 UTC by Aaron-G-9

Closes #84

2018-04-20 14:34 UTC, kdjohnson requested changes

2018-04-20 14:34 UTC, kdjohnson commented on src/App.js
> +    console.log("updateMonthViewClicked")
Remove this

2018-04-20 14:34 UTC, kdjohnson commented on src/components/MonthView.js
> +    const day = new Date(dateObject.year, dateObject.month - 3, dateObject.day)
?

2018-04-26 15:18 UTC, Aaron-G-9 commented on src/components/MonthView.js
> +    const day = new Date(dateObject.year, dateObject.month - 3, dateObject.day)
Oh man, nice catch. This is me forgetting to undo a hack to get fake data working. This would be horrible in production

2018-04-27 17:35 UTC, kdjohnson approved these changes

2018-04-27 18:33 UTC, merged